### ISSUE TITLE
 Issue with Nullable Property Initializing as "null" String Instead of Null Value

### ISSUE THREAD

**Issue by volkanakb** [andreaspenz/spryker-nos#25]
**Description of the Issue:**

When declaring a property with the TypeScript nullable syntax using the exclamation mark (`!`) along with `@attribute({ type: String })`, the expected behavior is that the property should be initialized as a `null` value. However, I have observed that the property is initialized as the string "null" instead.

**Steps to Reproduce:**

1. Create a class with a property declared as nullable using the exclamation mark (`!`) and decorated with `@attribute({ type: String })`.
2. Instantiate the class and check the initial value of the nullable property.

```typescript
import { attribute } from '@project-nos/spryker-decorators';

class MyClass {
  @attribute({ type: String })
  myNullableAttribute!: string | null;
}

const instance = new MyClass();
console.log(instance.myNullableAttribute); // Outputs "null" instead of null

**Comment by athopen** [comment]
@volkanakb thanks for your issue report.

Since we do not have access to the typescript declarations during runtime an auto-accessor with an attribute decorator
will always return the specified type. But in your case this should return an empty string rather than "null," indicating a clear bug. 

I'll work on a fix for this asap.

**Comment by athopen** [comment]
@volkanakb the bug has been fixed in the newest release https://github.com/project-nos/decorators/tree/v1.1.0
